# ruby service wrap for exchangerate-api.com

# rubocop:disable Layout/LineLength
module ServiceWrap2
  require 'httparty'
  require 'json'
  API = 'f7fe82122b36a865866bab5b'.freeze
  VERSION = 'v6'.freeze
  SERVICE_URL = "https://#{VERSION}.exchangerate-api.com/#{VERSION}/#{API}/latest/".freeze
  CURRENICES = {
    AED: %w[UAE-DIRHAM UNITED-ARAB-EMIRATES],
    ARS: %w[ARGENTINE-PESO ARGENTINA],
    AUD: %w[AUSTRALIAN-DOLLAR AUSTRALIA],
    BGN: %w[BULGARIAN-LEV BULGARIA],
    BRL: %w[BRAZILIAN-REAL BRAZIL],
    BSD: %w[BAHAMIAN-DOLLAR BAHAMAS],
    CAD: %w[CANADIAN-DOLLAR CANADA],
    CHF: %w[SWISS-FRANC SWITZERLAND],
    CLP: %w[CHILEAN-PESO CHILE],
    CNY: %w[CHINESE-RENMINBI CHINA],
    COP: %w[COLOMBIAN-PESO COLOMBIA],
    CZK: %w[CZECH-KORUNA CZECH-REPUBLIC],
    DKK: %w[DANISH-KRONE DENMARK],
    DOP: %w[DOMINICAN-PESO DOMINICAN-REPUBLIC],
    EGP: %w[EGYPTIAN-POUND EGYPT],
    EUR: ['EURO', %w[GERMANY AUSTRIA BELGIUM CYPRUS ESTONIA FINLAND FRANCE GREECE IRELAND ITALY LATVIA LITHUANIA MALTA NETHERLANDS PORTUGAL SLOVAKIA SLOVENIA SPAIN]],
    FJD: %w[FIJI-DOLLAR FIJI],
    GBP: %w[POUND-STERLING UNITED-KINGDOM],
    GTQ: %w[GUATEMALAN-QUETZAL GUATEMALA],
    HKD: %w[HONG-KONG-DOLLAR HONG-KONG],
    HRK: %w[CROATIAN-KUNA CROATIA],
    HUF: %w[HUNGARIAN-FORINT HUNGARY],
    IDR: %w[INDONESIAN-RUPIAH INDONESIA],
    ILS: %w[ISRAELI-NEW-SHEKEL ISRAEL],
    INR: %w[INDIAN-RUPEE INDIA],
    ISK: %w[ICELANDIC-KRONA ICELAND],
    JPY: %w[JAPANESE-YEN JAPAN],
    KRW: %w[SOUTH-KOREAN-WON SOUTH-KOREA],
    KZT: %w[KAZAKHSTANI-TENGE KAZAKHSTAN],
    MVR: %w[MALDIVIAN-RUFIYAA MALDIVES],
    MXN: %w[MEXICAN-PESO MEXICO],
    MYR: %w[MALAYSIAN-RINGGIT MALAYSIA],
    NOK: %w[NORWEGIAN-KRONE NORWAY],
    NZD: %w[NEW-ZEALAND-DOLLAR NEW-ZEALAND],
    PAB: %w[PANAMANIAN-BALBOA PANAMA],
    PEN: %w[PERUVIAN-SOL PERU],
    PHP: %w[PHILIPPINE-PESO PHILIPPINES],
    PKR: %w[PAKISTANI-RUPEE PAKISTAN],
    PLN: %w[POLISH-ZLOTY POLAND],
    PYG: %w[PARAGUAYAN-GUARANI PARAGUAY],
    RON: %w[ROMANIAN-LEU ROMANIA],
    RUB: %w[RUSSIAN-RUBLE RUSSIA],
    SAR: %w[SAUDI-RIYAL SAUDI-ARABIA],
    SEK: %w[SWEDISH-KRONA SWEDEN],
    SGD: %w[SINGAPORE-DOLLAR SINGAPORE],
    THB: %w[THAI-BAHT THAILAND],
    TRY: %w[TURKISH-LIRA TURKEY],
    TWD: %w[NEW-TAIWAN-DOLLAR TAIWAN],
    UAH: %w[UKRAINIAN-HRYVNIA UKRAINE],
    USD: %w[UNITED-STATES-DOLLAR UNITED-STATES],
    UYU: %w[URUGUAYAN-PESO URUGUAY],
    ZAR: %w[SOUTH-AFRICAN-RAND SOUTH-AFRICA]
  }.freeze
  private_constant :API

  def exchange_rate(pairs)
    ex_rate = []
    response = HTTParty.get(SERVICE_URL + pairs[0]).parsed_response
    pairs.each { |code| ex_rate << response['conversion_rates'][code] }
    ex_rate
  end
end

# rubocop:enable Layout/LineLength
